preservation_locations:
  - test-data/simple-loc
admin_email:
  - bbpennel@email.unc.edu
from_email: cdr-tps@unc.edu
activity_log:
  filename: ~
  level: "Logger::DEBUG"
  max_logs: ~
  max_size: ~
replica_path: ~
