preservation_locations:
  simple-tps-loc:
    path: test-data/simple-loc
    contacts:
      - test@example.com
admin_email:
  - test-admin@example.com
from_email: cdr-tps@unc.edu
activity_log:
  filename: ~
  level: "Logger::DEBUG"
  max_logs: ~
  max_size: ~
replica_paths:
  - ~
# Stored in sqlite3 time difference notation
periodic_validation_period: 5 minutes
complete_no_change_timeout: 12 hours