preservation_locations:
  simple-tps-loc:
    base_path: test-data/simple-loc
    bag_pattern: "*"
    contacts:
      - test@example.com
  invalid-loc:
    base_path: test-data/invalid-loc
    bag_pattern: "*"
admin_email:
  - test@example.com
from_email: pinecone@example.com
activity_log:
  filename: ~
  level: "Logger::DEBUG"
  max_logs: ~
  max_size: ~
replica_paths:
  - ./replicas
periodic_validation_period: 1 minute
complete_no_change_timeout: 0 minute