preservation_locations:
  simple-tps-loc:
    path: test-data/simple-loc
    contacts:
      - test@example.com
  invalid-loc:
    path: test-data/invalid-loc
admin_email:
  - test@example.com
from_email: cdr-tps@unc.edu
activity_log:
  filename: ~
  level: "Logger::DEBUG"
  max_logs: ~
  max_size: ~
replica_path: ./replicas
