preservation_locations:
  - test-data/simple-loc
  - test-data/invalid-loc
admin_email:
  - test@example.com
from_email: cdr-tps@unc.edu
activity_log:
  filename: ~
  level: "Logger::DEBUG"
  max_logs: ~
  max_size: ~
replica_dir: ./replicas
